modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Tamaized/Voidscape/issues"
license="All Rights Reserved"
[[mods]]
modId="voidscape"
version="${file.jarVersion}"
displayName="Voidscape"
credits=""
authors="Tamaized"
description='''

'''

[[dependencies.voidscape]]
    modId="neoforge"
    type="required"
    versionRange="[20,)"
    ordering="NONE"
    side="BOTH"