modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Tamaized/Voidscape/issues"
license="All Rights Reserved"
[[mods]]
modId="voidscape"
version="${version}"
displayName="Voidscape"
credits=""
authors="Tamaized"
description='''

'''