modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Tamaized/Voidscape/issues"
license="All Rights Reserved"
[[mods]]
modId="voidscape"
version="${file.jarVersion}"
displayName="Voidscape"
credits=""
authors="Tamaized"
description='''

'''

[[dependencies.voidscape]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"