modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Tamaized/Voidscape/issues"
license="All Rights Reserved"
[[mods]]
modId="voidscape"
version="${version}"
displayName="Voidscape"
credits=""
authors="Tamaized"
description='''

'''

[[dependencies.voidscape]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.75,)"
    ordering="NONE"
    side="BOTH"